create extension if not exists pgcrypto;

create table public.cities (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  color text not null,
  lat double precision,
  lng double precision,
  created_at timestamptz not null default now()
);

create table public.employees (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  auth_email text,
  name text not null,
  employee_type text not null check (employee_type in ('admin', 'technician', 'call_center')),
  city_id uuid references public.cities(id) on delete restrict,
  color text not null,
  phone text,
  can_view_technician_cards boolean not null default false,
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint technicians_require_city check (
    (employee_type = 'technician' and city_id is not null)
    or (employee_type in ('admin', 'call_center'))
  )
);

create table public.employee_private (
  employee_id uuid primary key references public.employees(id) on delete cascade,
  passport text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sources (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  city_id uuid not null references public.cities(id) on delete restrict,
  technician_id uuid not null references public.employees(id) on delete restrict,
  created_by uuid references public.employees(id) on delete set null,
  direction_id uuid references public.service_catalog(id) on delete set null,
  subcategory_id uuid references public.service_catalog(id) on delete set null,
  order_date date not null,
  time_slot smallint not null check (time_slot between 0 and 12),
  duration_slots smallint not null default 2 check (duration_slots between 1 and 12),
  price numeric,
  final_price numeric,
  district text,
  client_name text,
  client_phone text,
  address text,
  lat double precision,
  lng double precision,
  comment text,
  status text not null default 'Новый' check (status in ('Новый', 'Прозвонен', 'Подтверждён', 'Подтвержден мастером', 'В пути', 'На объекте', 'Выполнен', 'Отменён', 'Перенесён', 'Возврат в офис')),
  technician_confirmed_at timestamptz,
  technician_confirmed_by uuid references public.employees(id) on delete set null,
  returned_to_office_at timestamptz,
  returned_to_office_by uuid references public.employees(id) on delete set null,
  return_to_office_comment text,
  office_attention_required boolean not null default false,
  source_id uuid references public.sources(id) on delete set null,
  work_order text,
  work_done text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_number),
  unique (technician_id, order_date, time_slot)
);

create table public.employee_service_scopes (
  employee_id uuid not null references public.employees(id) on delete cascade,
  direction_id uuid not null references public.service_catalog(id) on delete cascade,
  subcategory_id uuid not null references public.service_catalog(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (employee_id, subcategory_id)
);

create table public.order_service_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  service_id uuid not null references public.service_catalog(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric not null default 0,
  created_at timestamptz not null default now(),
  unique (order_id, service_id)
);

create table public.day_offs (
  technician_id uuid not null references public.employees(id) on delete cascade,
  off_date date not null,
  created_by uuid references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (technician_id, off_date)
);

create table public.busy_slots (
  technician_id uuid not null references public.employees(id) on delete cascade,
  busy_date date not null,
  time_slot smallint not null check (time_slot between 0 and 12),
  created_by uuid references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (technician_id, busy_date, time_slot)
);

create table public.service_catalog (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references public.service_catalog(id) on delete cascade,
  node_type text not null check (node_type in ('direction', 'subcategory', 'service')),
  name text not null,
  price numeric,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_catalog_price_rule check (
    (node_type = 'service' and price is not null and price >= 0)
    or (node_type in ('direction', 'subcategory') and price is null)
  )
);

create table public.order_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  actor_employee_id uuid references public.employees(id) on delete set null,
  action text not null,
  field_name text,
  old_value text,
  new_value text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.employees e
    where e.auth_user_id = auth.uid()
      and e.employee_type = 'admin'
  );
$$;

create or replace function public.current_employee_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select e.id
  from public.employees e
  where e.auth_user_id = auth.uid()
  limit 1
$$;

create or replace function public.current_employee_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select e.employee_type
  from public.employees e
  where e.auth_user_id = auth.uid()
  limit 1
$$;

create or replace function public.can_current_user_manage_orders()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.employees e
    where e.auth_user_id = auth.uid()
      and e.employee_type in ('admin', 'call_center')
  )
$$;

create or replace function public.can_current_user_delete_orders()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.employees e
    where e.auth_user_id = auth.uid()
      and e.employee_type = 'admin'
  )
$$;

create or replace function public.can_current_user_view_technician_cards()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.employees e
    where e.auth_user_id = auth.uid()
      and (
        e.employee_type = 'admin'
        or (e.employee_type = 'call_center' and e.can_view_technician_cards = true)
      )
  )
$$;

create or replace function public.touch_presence()
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  touched timestamptz;
begin
  update public.employees
  set last_seen = now()
  where auth_user_id = auth.uid()
  returning last_seen into touched;

  return touched;
end;
$$;

grant execute on function public.touch_presence() to authenticated;
grant execute on function public.current_employee_id() to authenticated;
grant execute on function public.current_employee_role() to authenticated;
grant execute on function public.can_current_user_manage_orders() to authenticated;
grant execute on function public.can_current_user_delete_orders() to authenticated;
grant execute on function public.can_current_user_view_technician_cards() to authenticated;

create trigger employees_set_updated_at before update on public.employees
for each row execute function public.set_updated_at();

create trigger employee_private_set_updated_at before update on public.employee_private
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

create trigger service_catalog_set_updated_at before update on public.service_catalog
for each row execute function public.set_updated_at();

alter table public.cities enable row level security;
alter table public.employees enable row level security;
alter table public.employee_private enable row level security;
alter table public.sources enable row level security;
alter table public.orders enable row level security;
alter table public.day_offs enable row level security;
alter table public.busy_slots enable row level security;
alter table public.order_history enable row level security;
alter table public.service_catalog enable row level security;

create policy "authenticated read cities" on public.cities
for select to authenticated using (true);

create policy "admin manage cities" on public.cities
for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

create policy "authenticated read employees" on public.employees
for select to authenticated using (true);

create policy "authenticated read sources" on public.sources
for select to authenticated using (true);

create policy "admin and call center create sources" on public.sources
for insert to authenticated with check (exists (
  select 1
  from public.employees e
  where e.auth_user_id = auth.uid()
    and e.employee_type in ('admin', 'call_center')
));

create policy "crm roles read orders" on public.orders
for select to authenticated using (
  public.can_current_user_manage_orders()
  or technician_id in (
    select e.id from public.employees e where e.auth_user_id = auth.uid()
  )
);

create policy "crm roles insert orders" on public.orders
for insert to authenticated with check (public.can_current_user_manage_orders());

create policy "crm roles update orders" on public.orders
for update to authenticated
using (
  public.can_current_user_manage_orders()
  or technician_id = public.current_employee_id()
)
with check (
  public.can_current_user_manage_orders()
  or technician_id = public.current_employee_id()
);

create policy "admin delete orders only" on public.orders
for delete to authenticated using (public.can_current_user_delete_orders());

create policy "admin read employee private" on public.employee_private
for select to authenticated using (public.is_admin_user());

create policy "admin manage employees" on public.employees
for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

create policy "admin manage employee private" on public.employee_private
for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

create policy "authenticated read history" on public.order_history
for select to authenticated using (true);

create policy "crm roles insert history" on public.order_history
for insert to authenticated with check (
  public.can_current_user_manage_orders()
  or exists (
    select 1
    from public.orders o
    where o.id = order_id
      and o.technician_id = public.current_employee_id()
  )
);

create policy "authenticated read day offs" on public.day_offs
for select to authenticated
using (
  public.current_employee_role() in ('admin', 'call_center')
  or exists (
    select 1
    from public.employees e
    where e.id = technician_id
      and e.id = public.current_employee_id()
  )
);

create policy "admin and call center manage day offs" on public.day_offs
for all to authenticated
using (public.current_employee_role() in ('admin', 'call_center'))
with check (public.current_employee_role() in ('admin', 'call_center'));

create policy "authenticated read busy slots" on public.busy_slots
for select to authenticated
using (
  public.current_employee_role() in ('admin', 'call_center')
  or technician_id = public.current_employee_id()
);

create policy "crm roles manage busy slots" on public.busy_slots
for all to authenticated
using (
  public.current_employee_role() in ('admin', 'call_center')
  or technician_id = public.current_employee_id()
)
with check (
  public.current_employee_role() in ('admin', 'call_center')
  or technician_id = public.current_employee_id()
);

create policy "authenticated read service catalog" on public.service_catalog
for select to authenticated using (true);

create policy "admin manage service catalog" on public.service_catalog
for all to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

create index if not exists idx_employees_last_seen on public.employees(last_seen);
create index if not exists idx_orders_technician_date on public.orders(technician_id, order_date);
create index if not exists idx_busy_slots_technician_date on public.busy_slots(technician_id, busy_date);
create index if not exists service_catalog_parent_idx on public.service_catalog(parent_id, sort_order, created_at);
create unique index if not exists service_catalog_unique_name_per_parent on public.service_catalog(coalesce(parent_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(name));
