do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'order_number'
  ) then
    alter table public.orders
      add column order_number bigint generated by default as identity;
  end if;
end $$;

with numbered as (
  select id, row_number() over (order by created_at asc, id asc) - 1 as new_number
  from public.orders
  where order_number is null
)
update public.orders o
set order_number = numbered.new_number
from numbered
where o.id = numbered.id;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_order_number_key'
  ) then
    alter table public.orders
      add constraint orders_order_number_key unique (order_number);
  end if;
end $$;
